
%% Build Control Triple Pendulum S-function
path = pwd;

cd(fullfile('sfun'));

mex('-I..\util',...
    ['-I' fullfile(path,'libzmq','include')],...
    ['-I' fullfile(path, 'cppzmq')],...
    ['-L' fullfile(path, 'libzmq','bin')],...
    '-llibzmq','-llibzmq-v142-mt-4_3_4',...
    'controluntriplnsfun.cpp',...
    'controluntriplnclient.cpp',...
    fullfile(path, 'util','statcal_util.cpp'));

% %% Build Acrobot Control S-function
% cd(fullfile(p.RootFolder,'CoSimExample','sfun'));
% 
% mex('-I..\util',...
%     ['-I' fullfile(p.RootFolder,'libzmq','include')],...
%     ['-I' fullfile(p.RootFolder,'cppzmq')],...
%     ['-L' fullfile(p.RootFolder,'libzmq','bin')],...
%     '-llibzmq','-llibzmq-v142-mt-4_3_4',...
%     'acrobotsfun.cpp',...
%     'acrobotclient.cpp',...
%     fullfile(p.RootFolder,'CoSimExample','util','statcal_util.cpp'));
% 
% cd(p.RootFolder)
% 
% extend MATLAB search path